### ISSUE TITLE
Mothim beats Volcarona due to Volcarona using the wrong strategy

### ISSUE THREAD

**Issue by mcolotto** [fonse/pokemon-battle#12]
Sample fight:

```
@fonso's Volcarona used Acrobatics!
It's super effective!
Your Mothim is hit for 204 HP (73%)

Your Mothim used Acrobatics!
It's super effective!
@fonso's Volcarona is hit for 311 HP (100%)
@fonso's Volcarona fainted!


You defeated @fonso!
Mothim: 77 HP (27%) left.
```

Mothim has def == sp. def, but Volcarona has much higher sp. atk than atk. Volcarona should use Fire Blast instead of Acrobatics; Fire Blast would KO Mothim in one hit.

http://bulbapedia.bulbagarden.net/wiki/Volcarona

http://bulbapedia.bulbagarden.net/wiki/Mothim

**Comment by fonse** [comment]
Fixed in 5e98218.

The 2x multiplier for choosing Acrobatics was being applied twice, resulting in a total of 4x.
Now Volcarona will choose Fire Blast when facing Mothim.
